---
# maintains file name, binary names, and anything which is not a directory or path

# Environment file names
sequencer_environment_secrets_file_name: "{{ service_identifier }}.secrets.env"
sequencer_environment_general_file_name: "{{ service_identifier }}.env"

sequencer_p2p_private_key_name: p2p-private-key
