---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    aztec:
      hosts:
        validator.aztec.testnet.encapsulate.xyz:
          type: validator
